version: '3'

services:
  postgres-server:
    env_file:
      - .env
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${USERPASSWORD}
      POSTGRES_DB: ${DBNAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${USERNAME}", "-d", "${DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  tarveller-data-generator:
    build:
      context: .
      dockerfile: traveller.Dockerfile
    container_name: traveller-data-generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]

  visitareainfo-data-generator:
    build:
      context: .
      dockerfile: visitareainfo.Dockerfile
    container_name: visitareainfo-data-generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]

networks:
  default:
    name: mlops-network